In [1]:
import pandas as pd
import re

# **Load Data**

In [2]:
url = 'https://raw.githubusercontent.com/naiarch/UTS-Big-Data-Web-Scraping-Lazada/main/products_sociolla.csv'

df = pd.read_csv(url)
df.head()

,brand_name,product_name,product_id,beauty_point_earned,price_range,price_by_combinations,url,active_date,default_category,categories,rating_types_str,average_rating,total_reviews,average_rating_by_types,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
0,796_3ce,MULTI EYE COLOR PALETTE,97802,130,Rp 555.000 - Rp 687.000,NaN,https://www.sociolla.com/eyeshadow/69460-phan-...,2022-10-03T03:30:06.681Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.920000,5,"""star_long_wear"": 5; ""star_packaging"": 4.8; ""s...",5,0,0,5,717
1,796_3ce,VELVET LIP TINT,97810,50,Rp 264.000,NaN,https://www.sociolla.com/lip-cream/69468-son-k...,2022-10-03T03:02:40.340Z,Lip Cream,Makeup; Lips; Lip Cream,is_star_long_wear;is_star_packaging;is_star_pi...,4.576190,42,"""star_long_wear"": 4.309523809523809; ""star_pac...",42,10,2,30,682
2,796_3ce,LIP COLOR,97822,60,Rp 317.000,NaN,https://www.sociolla.com/lip-matte/69480-son-t...,2023-05-30T09:49:15.158Z,Lipstick,Makeup; Lips; Lipstick,is_star_long_wear;is_star_packaging;is_star_pi...,0.000000,0,NaN,0,0,0,0,173
3,796_3ce,MINI MULTI EYE COLOR PALETTE,97833,80,Rp 423.000,NaN,https://www.sociolla.com/eyeshadow/69491-phan-...,2022-10-03T03:27:01.334Z,Eyeshadow,Makeup; Eyes; Eyeshadow,is_star_long_wear;is_star_packaging;is_star_pi...,4.883333,6,"""star_long_wear"": 4.916666666666667; ""star_pac...",12,1,0,11,257
4,796_3ce,FACE BLUSH,97801,60,Rp 300.000,NaN,https://www.sociolla.com/blush/69459-phan-ma-h...,2022-10-03T03:22:26.610Z,Blush,Makeup; Face; Blush,is_star_long_wear;is_star_packaging;is_star_pi...,4.858824,13,"""star_long_wear"": 4.9411764705882355; ""star_pa...",17,2,0,15,387

In [3]:
df.tail()

,brand_name,product_name,product_id,beauty_point_earned,price_range,price_by_combinations,url,active_date,default_category,categories,rating_types_str,average_rating,total_reviews,average_rating_by_types,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
7631,273_yves-rocher,Ambre Noir Eau De Toilette,2158,130,Rp 659.000,NaN,https://sociolla.com/fragrance/8088-ambre-noir...,NaN,Eau De Toilette,Shop By Departments; Home; UOBMon,is_star_long_wear;is_star_packaging;is_star_va...,4.476190,7,"""star_long_wear"": 4.285714285714286; ""star_pac...",6,1,2,4,355
7632,273_yves-rocher,Soin Stimulating Conditioner,64174,30,Rp 199.000,NaN,https://vn.sociolla.com/d-u-x/17239-soin-stimu...,NaN,Conditioner,Hair Care; Shampoo; Conditioner,is_star_effectiveness;is_star_packaging;is_sta...,4.638889,9,"""star_effectiveness"": 4.444444444444445; ""star...",7,1,2,6,122
7633,273_yves-rocher,Repair Hair Mask,36357,50,Rp 289.000,NaN,https://www.sociolla.com/hair-mask/14833-repai...,2022-10-27T07:33:19.380Z,Hair Mask,Hair Care; Hair Treatment; Hair Mask,is_star_effectiveness;is_star_packaging;is_sta...,4.750000,5,"""star_effectiveness"": 5; ""star_packaging"": 5; ...",5,1,0,4,58
7634,273_yves-rocher,Hand Cream Olive Petitgrain,36404,20,Rp 109.000,NaN,https://www.sociolla.com/221-hand-and-foot-cre...,NaN,Hand & Foot Cream,Shop By Departments; Home; 12.12 PRICE POINT 50%,is_star_effectiveness;is_star_packaging;is_sta...,4.968750,8,"""star_effectiveness"": 5; ""star_packaging"": 5; ...",8,2,0,6,117
7635,273_yves-rocher,Color Mask,64153,50,Rp 289.000,NaN,https://vn.sociolla.com/kem-t-c/17224-color-mask,2023-09-20T10:38:15.154Z,Hair Mask,Hair Care; Hair Treatment; Hair Mask,is_star_effectiveness;is_star_packaging;is_sta...,4.500000,2,"""star_effectiveness"": 4.5; ""star_packaging"": 4...",2,1,0,1,35

# **Informasi Data**

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7636 entries, 0 to 7635
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   brand_name                    7636 non-null   object
 1   product_name                  7636 non-null   object
 2   product_id                    7636 non-null   int64
 3   beauty_point_earned           7636 non-null   int64
 4   price_range                   7636 non-null   object
 5   price_by_combinations         4087 non-null   object
 6   url                           7636 non-null   object
 7   active_date                   5534 non-null   object
 8   default_category              7636 non-null   object
 9   categories                    7632 non-null   object
 10  rating_types_str              7561 non-null   object
 11  average_rating                7636 non-null   float64
 12  total_reviews                 7636 non-null   int64
 13  average_rating_by_types       5790 non-null   object
 14  total_recommended_count       7636 non-null   int64
 15  total_repurchase_maybe_count  7636 non-null   int64
 16  total_repurchase_no_count     7636 non-null   int64
 17  total_repurchase_yes_count    7636 non-null   int64
 18  total_in_wishlist             7636 non-null   int64
dtypes: float64(1), int64(8), object(10)
memory usage: 1.1+ MB

# **Cek Duplikasi Data**

In [5]:
df.duplicated().sum()

np.int64(0)

# **Cek Missing Value**

In [6]:
df.isnull().sum()

brand_name                         0
product_name                       0
product_id                         0
beauty_point_earned                0
price_range                        0
price_by_combinations           3549
url                                0
active_date                     2102
default_category                   0
categories                         4
rating_types_str                  75
average_rating                     0
total_reviews                      0
average_rating_by_types         1846
total_recommended_count            0
total_repurchase_maybe_count       0
total_repurchase_no_count          0
total_repurchase_yes_count         0
total_in_wishlist                  0
dtype: int64

In [7]:
# @title drop kolom
df = df.drop(columns=['brand_name', 'product_id', 'price_by_combinations', 'beauty_point_earned', 'url', 'active_date', 'default_category', 'categories', 'rating_types_str', 'average_rating_by_types'])
df

,product_name,price_range,average_rating,total_reviews,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist
0,MULTI EYE COLOR PALETTE,Rp 555.000 - Rp 687.000,4.920000,5,5,0,0,5,717
1,VELVET LIP TINT,Rp 264.000,4.576190,42,42,10,2,30,682
2,LIP COLOR,Rp 317.000,0.000000,0,0,0,0,0,173
3,MINI MULTI EYE COLOR PALETTE,Rp 423.000,4.883333,6,12,1,0,11,257
4,FACE BLUSH,Rp 300.000,4.858824,13,17,2,0,15,387
...,...,...,...,...,...,...,...,...,...
7631,Ambre Noir Eau De Toilette,Rp 659.000,4.476190,7,6,1,2,4,355
7632,Soin Stimulating Conditioner,Rp 199.000,4.638889,9,7,1,2,6,122
7633,Repair Hair Mask,Rp 289.000,4.750000,5,5,1,0,4,58
7634,Hand Cream Olive Petitgrain,Rp 109.000,4.968750,8,8,2,0,6,117
7635,Color Mask,Rp 289.000,4.500000,2,2,1,0,1,35

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7636 entries, 0 to 7635
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   product_name                  7636 non-null   object
 1   price_range                   7636 non-null   object
 2   average_rating                7636 non-null   float64
 3   total_reviews                 7636 non-null   int64
 4   total_recommended_count       7636 non-null   int64
 5   total_repurchase_maybe_count  7636 non-null   int64
 6   total_repurchase_no_count     7636 non-null   int64
 7   total_repurchase_yes_count    7636 non-null   int64
 8   total_in_wishlist             7636 non-null   int64
dtypes: float64(1), int64(6), object(2)
memory usage: 537.0+ KB

# **Adjusting Column**

In [9]:
# @title kolom harga
def clean_and_average_price(price_str):
    cleaned = re.sub(r'[^\d\-]', '', str(price_str))
    if not cleaned:
        return 0.0
    if '-' in cleaned:
        prices = cleaned.split('-')
        valid_prices = [float(p) for p in prices if p]
        return sum(valid_prices) / len(valid_prices) if valid_prices else 0.0
    else:
        return float(cleaned)

df['harga'] = df['price_range'].apply(clean_and_average_price)
df = df.drop(columns=['price_range'])
df

,product_name,average_rating,total_reviews,total_recommended_count,total_repurchase_maybe_count,total_repurchase_no_count,total_repurchase_yes_count,total_in_wishlist,harga
0,MULTI EYE COLOR PALETTE,4.920000,5,5,0,0,5,717,621000.0
1,VELVET LIP TINT,4.576190,42,42,10,2,30,682,264000.0
2,LIP COLOR,0.000000,0,0,0,0,0,173,317000.0
3,MINI MULTI EYE COLOR PALETTE,4.883333,6,12,1,0,11,257,423000.0
4,FACE BLUSH,4.858824,13,17,2,0,15,387,300000.0
...,...,...,...,...,...,...,...,...,...
7631,Ambre Noir Eau De Toilette,4.476190,7,6,1,2,4,355,659000.0
7632,Soin Stimulating Conditioner,4.638889,9,7,1,2,6,122,199000.0
7633,Repair Hair Mask,4.750000,5,5,1,0,4,58,289000.0
7634,Hand Cream Olive Petitgrain,4.968750,8,8,2,0,6,117,109000.0
7635,Color Mask,4.500000,2,2,1,0,1,35,289000.0

In [10]:
# @title kolom jumlah_terjual
df['jumlah_terjual'] = (
    df['total_repurchase_maybe_count'] +
    df['total_repurchase_no_count'] +
    df['total_repurchase_yes_count']
)

kolom_yang_didrop = ['total_repurchase_maybe_count', 'total_repurchase_no_count',
                     'total_repurchase_yes_count']
df = df.drop(columns=kolom_yang_didrop)
df

,product_name,average_rating,total_reviews,total_recommended_count,total_in_wishlist,harga,jumlah_terjual
0,MULTI EYE COLOR PALETTE,4.920000,5,5,717,621000.0,5
1,VELVET LIP TINT,4.576190,42,42,682,264000.0,42
2,LIP COLOR,0.000000,0,0,173,317000.0,0
3,MINI MULTI EYE COLOR PALETTE,4.883333,6,12,257,423000.0,12
4,FACE BLUSH,4.858824,13,17,387,300000.0,17
...,...,...,...,...,...,...,...
7631,Ambre Noir Eau De Toilette,4.476190,7,6,355,659000.0,7
7632,Soin Stimulating Conditioner,4.638889,9,7,122,199000.0,9
7633,Repair Hair Mask,4.750000,5,5,58,289000.0,5
7634,Hand Cream Olive Petitgrain,4.968750,8,8,117,109000.0,8
7635,Color Mask,4.500000,2,2,35,289000.0,2

In [12]:
# @title fixed column
df['toko'] = 'Sociolla'

kolom_baru = {
    'product_name': 'nama_produk',
    'average_rating': 'rating',
    'total_reviews': 'jumlah_review',
    'total_recommended_count': 'jumlah_direkomendasikan',
    'total_in_wishlist': 'jumlah_wishlist'
}
df = df.rename(columns=kolom_baru)

urutan_kolom = [
    'toko',
    'nama_produk',
    'harga',
    'rating',
    'jumlah_review',
    'jumlah_terjual',
    'jumlah_direkomendasikan',
    'jumlah_wishlist'
]
df = df[urutan_kolom]

df

,toko,nama_produk,harga,rating,jumlah_review,jumlah_terjual,jumlah_direkomendasikan,jumlah_wishlist
0,Sociolla,MULTI EYE COLOR PALETTE,621000.0,4.920000,5,5,5,717
1,Sociolla,VELVET LIP TINT,264000.0,4.576190,42,42,42,682
2,Sociolla,LIP COLOR,317000.0,0.000000,0,0,0,173
3,Sociolla,MINI MULTI EYE COLOR PALETTE,423000.0,4.883333,6,12,12,257
4,Sociolla,FACE BLUSH,300000.0,4.858824,13,17,17,387
...,...,...,...,...,...,...,...,...
7631,Sociolla,Ambre Noir Eau De Toilette,659000.0,4.476190,7,7,6,355
7632,Sociolla,Soin Stimulating Conditioner,199000.0,4.638889,9,9,7,122
7633,Sociolla,Repair Hair Mask,289000.0,4.750000,5,5,5,58
7634,Sociolla,Hand Cream Olive Petitgrain,109000.0,4.968750,8,8,8,117
7635,Sociolla,Color Mask,289000.0,4.500000,2,2,2,35

# **Menyimpan Dataset Sociolla**

In [13]:
df.to_csv('products_sociolla_clean.csv', index=False)
print("Dataset berhasil disimpan dengan nama 'products_sociolla_clean.csv'!")

Dataset berhasil disimpan dengan nama 'products_sociolla_clean.csv'!